/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutPage { 'instagramHandle' : string, 'aboutText' : string }
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export interface DeliveryAddress {
  'city' : string,
  'fullName' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phone' : string,
  'pincode' : string,
}
export type IdempotenceResult = { 'success' : null } |
  { 'alreadyInitialized' : null };
export interface OrderItem {
  'productId' : string,
  'quantity' : bigint,
  'priceAtOrder' : bigint,
}
export interface OrderRecord {
  'id' : string,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'paymentMethod' : PaymentMethod,
  'user' : Principal,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'delivered' : null };
export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null };
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'isOnSale' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'salePrice' : [] | [bigint],
  'price' : bigint,
}
export interface Promotion {
  'title' : string,
  'discountInfo' : string,
  'description' : string,
  'imageUrl' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreConfig { 'upiId' : string }
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addPromotion' : ActorMethod<[Promotion], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[DeliveryAddress, PaymentMethod], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAboutPage' : ActorMethod<[], AboutPage>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getMyOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getOnSaleProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[string], OrderRecord>,
  'getOrdersAdmin' : ActorMethod<[], Array<OrderRecord>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getPromotions' : ActorMethod<[], Array<Promotion>>,
  'getStoreConfig' : ActorMethod<[], StoreConfig>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], IdempotenceResult>,
  'initializeStore' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removePromotion' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAboutPage' : ActorMethod<[AboutPage], undefined>,
  'updateCartItem' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];